version: '2'
services:

  bitcoind-api-be:
    image: bitcoind-api-be:latest
    build:
      context: .
      dockerfile: $PWD/Dockerfile
    environment:
      - DB_HOST=www.excluserv.co.uk
      - DB_PORT=25432
      - APP_SECRET=9oPWfwjAhsdUyJoMHLUK9l0hjJgyvhlu7
    ports:
      - "4001:4001"
    networks:
      - bitcoind
    volumes:
      - .:/usr/src/app

networks:
  bitcoind:
    external: true
