
restore_workspace: &restore_workspace
  attach_workspace:
    at: .

save_workspace: &save_workspace
  persist_to_workspace:
    root: .
    paths:
      - .

version: 2
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - base-install
      - lint:
          requires:
            - base-install
      - tag:
          requires:
            - base-install
            - lint
          filters:
            branches:
              only:
                - master
      - slack_info:
          requires:
            - base-install
            - lint
            - tag
          filters:
            branches:
              only:
                - master

jobs:
  base-install:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Install Node Dependencies
          command: yarn install
      - *save_workspace

  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - *restore_workspace
      - attach_workspace:
          at: ~/code
      - run:
          name: Lint source
          command: yarn lint

  slack_info:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - *restore_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Inform Slack-Channel
          command: |
            curl -X POST --data-urlencode "payload={\"channel\": \"#$SLACK_CHANNEL\", \"username\": \"webhookbot\", \"text\": \"Push ($CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM])\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/$SLACK_KEY
  tag:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - *restore_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Start Docker Container
          command: |
            PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
            echo 'export PACKAGE_VERSION=$PACKAGE_VERSION' >> $BASH_ENV
            source $BASH_ENV
            echo "PACKAGE_VERSION="+$PACKAGE_VERSION
            echo "CIRCLE_BUILD_NUM="+$CIRCLE_BUILD_NUM
            echo "CIRCLE_BRANCH="+$CIRCLE_BRANCH
            echo "CIRCLE_BUILD_NUM="+$CIRCLE_BUILD_NUM
            echo "CIRCLE_BUILD_NUM"+$CIRCLE_BUILD_NUM
            echo "CIRCLE_PR_REPONAME="+$CIRCLE_PR_REPONAME
            echo "CIRCLE_PROJECT_REPONAME="+$CIRCLE_PROJECT_REPONAME
            echo "CIRCLE_TAG="+$CIRCLE_TAG
            echo "VERSION="+$VERSION
            docker build -t cbaus/bitcoind-api-be:$PACKAGE_VERSION.$CIRCLE_BUILD_NUM .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            #docker commit `docker ps -a|grep 'bitcoind-api-be'|cut -d' ' -f1` bitcoind-api-be
            docker tag cbaus/bitcoind-api-be:$PACKAGE_VERSION.$CIRCLE_BUILD_NUM cbaus/bitcoind-api-be:latest
            docker push cbaus/bitcoind-api-be:$PACKAGE_VERSION.$CIRCLE_BUILD_NUM
            docker push cbaus/bitcoind-api-be:latest
