# Download cached workspace
restore_workspace: &restore_workspace
  attach_workspace:
    # Must be absolute path or relative path from working_directory
    at: .

# Save all actual files
save_workspace: &save_workspace
  persist_to_workspace:
    # Must be relative path from working_directory
    root: .
    # Must be relative path from root
    paths:
      - .


version: 2
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - base-install
      - build:
          requires:
            - base-install
          filters:
            branches:
              only:
                - master
      - lint:
          requires:
            - base-install
            - build
      - tag:
          requires:
            - base-install
            - build
            - lint
          filters:
            branches:
              only:
                - master
      - slack_info:
          requires:
            - base-install
            - build
            - lint
            - tag
          filters:
            branches:
              only:
                - master

jobs:
  base-install:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Install Node Dependencies
          command: yarn install
      - *save_workspace

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Container
          command: docker-compose build

  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - *restore_workspace
      - attach_workspace:
          at: ~/code
      - run:
          name: Lint source
          command: yarn lint
  slack_info:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - *restore_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Inform Slack-Channel
          command: |
            curl -X POST --data-urlencode "payload={\"channel\": \"#excluserv_general\", \"username\": \"webhookbot\", \"text\": \"New Docker-Image [] pushed to remote.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/$SLACK_KEY
  tag:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - *restore_workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Start Docker Container
          command: |
            echo "DOCKER" + $DOCKER_LOGIN + " " + `docker ps -a|grep 'bitcoind-api-be'|cut -d' ' -f1`
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker commit `docker ps -a|grep 'bitcoind-api-be'|cut -d' ' -f1` bitcoind-api-be
            docker tag bitcoind-api-be cbaus/bitcoind-api-be
            docker push cbaus/bitcoind-api-be
