version: 2
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - base-install
      - build:
          requires:
            - base-install
          filters:
            branches:
              only:
                - master
      - lint:
          requires:
            - base-install
            - build
      - tag:
          requires:
            - base-install
            - build
            - lint
          filters:
            branches:
              only:
                - master

jobs:
  base-install:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Container
          command: docker-compose build

  lint:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - attach_workspace:
          at: ~/code
      - run:
          name: Lint source
          command: yarn lint

  tag:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Start Docker Container
          command: |
            docker-compose build
            DOCKER_ID=`docker ps -a|grep 'bitcoind-api-be'|cut -d' ' -f1`
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker commit $DOCKER_ID bitcoind-api-be
            docker tag bitcoind-api-be cbaus/bitcoind-api-be
            docker push cbaus/bitcoind-api-be
