version: 2
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - base-install
      - build:
          requires:
            - base-install
          filters:
            branches:
              only:
                - master
jobs:
  base-install:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
          requires:
            - base-install

  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/code
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - base-install
      - run:
          name: Build Docker Container
          command: docker-compose build
          requires:
            - base-install
